# If set to db, then use DB table to store gateways,
# useful when your run many gateways on the same server.
gateways_source: config

# Used to encrypt gateway secrets in the DB.
server_secret: 'global server secret'

gateways:

  default:
    pubkey: 'xpub-000'
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: true
    callback_url: 'http://localhost:3000/payment-callback'
    default_currency: 'BTC'
    orders_expiration_period: 900 # seconds
    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp
  second_gateway:
    pubkey: 'xpub-001'
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: false
    callback_url: 'http://localhost:3001/payment-callback'
    default_currency: 'BTC'
    orders_expiration_period: 300 # seconds
    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp

db:
  adapter: sqlite
  name: straight.db
