# If set to db, then use DB table to store gateways,
# useful when your run many gateways on the same server.
gateways_source: config
environment: test
count_orders: true
expiration_overtime: 0
reuse_address_orders_threshold: 5

gateways:

  default:
    pubkey: 'xpub-000'
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: true
    callback_url: 'http://localhost:3000/payment-callback'
    default_currency: 'BTC'
    orders_expiration_period: 900 # seconds
    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp
    active: true
  second_gateway:
    pubkey: 'xpub-001'
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: false
    callback_url: 'http://localhost:3001/payment-callback'
    default_currency: 'BTC'
    orders_expiration_period: 300 # seconds
    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp
    active: true

blockchain_adapters:
  - BlockchainInfo
  - Mycelium

db:
  adapter: sqlite
  name: straight.db

redis:
  host: localhost
  port: 6379
  db:   null
  password: null
