# If set to db, then use DB table to store gateways,
# useful when your run many gateways on the same server.
gateways_source: config

gateways:

  default:
    pubkey: 'xpub-000'
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: true
  second_gateway:
    pubkey: 'xpub-001'
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: false

db:
  adapter: sqlite
  name: straight.db
