# If set to db, then use DB table to store gateways,
# useful when your run many gateways on the same server.
gateways_source: config

gateways:
  default:
    pubkey: xpub-xxx # <- TODO: change this to your BIP32 pubkey
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: false
    callback_url: 'http://localhost:3000/my_app/payment_callback'
    default_currency: 'BTC'

    # The order matters here, we check for prices with the first adapter,
    # if it fails, move on to the next
    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp

logmaster:
  log_level: INFO # Wise to change to WARN for production
  file: straight.log
  raise_exception: false 
  name: Straight server logger

  # These options bellow send you email whenever a FATAL error occurs.
  # You probably want to uncomment them for production.
  #
  #email_config:
    #to: 'me@email.foo',
    #from: "logmaster@yourapp.com"

db:
  adapter: sqlite
  name: straight.db # file is always located in ~/.straight

  # No need to set these options for sqlite,
  # but other DBs may require them.
  #
  #user: username
  #password: password
  #host: hostname
  #port: 1234
